# Generated by Django 3.0.4 on 2020-04-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageFile', '0007_auto_20200417_1354'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getmodel',
            name='connKey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageFile.ImageModel'),
        ),
    ]
