# Generated by Django 3.0.4 on 2020-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='uploadedDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='userName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
