# Generated by Django 3.0.4 on 2020-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageFile', '0007_auto_20200417_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testName', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
