# Generated by Django 3.0.4 on 2020-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploadedDate', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('imageColumn', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
