# Generated by Django 3.0.4 on 2020-04-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestExcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('age', models.CharField(max_length=250, null=True)),
                ('gender', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
